server:
  applicationConnectors:
    - type: http
      port: 1234
  adminConnectors:
    - type: http
      port: 1235

#rateLimiter:
#  tokenBucket:
#    tokensPerSecond: 1
#    maxTokens: 10
#  FixedCounterWindow:
#    tokensPerSecond: 1
#    maxTokens: 10
#  SlidingCounterWindow:
#    tokensPerSecond: 1
#    maxTokens: 10